#!/bin/zsh
set -eu
set -o pipefail

if [[ $# -lt 2 ]]; then
    eout "Usage: ./watch_and_run day_number input"
    exit 1
fi

day_number=$1; shift
input="$1"; shift

print_input()
{
    iout "$(cat <<< "$input")"
}

run_script()
{
    clear; print_input; elixir day_$day_number.exs <<< "$input" && sout || eout; date
}

run_script

fswatch -0 day_$day_number.exs | while read -d "" event; do
    run_script
done

